services:
  risk-calculator:
    container_name: risk-calculator
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - '5000:5000'
    healthcheck:
      test: ["CMD", "python", "webapp/health.py"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
